version: '3.8'

services:
  bot:
    build: .
    container_name: weather_telegram_bot
    env_file:
      - .env
    depends_on:
      - redis
    volumes:
      - .:/app
    restart: always

  redis:
    image: redis:alpine
    container_name: weather_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
